"""
Django settings for productivity_plugin_api project.

Generated by 'django-admin startproject' using Django 5.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path
from productivity_plugin_api.config import DB_CONFIG
from dotenv import load_dotenv
from datetime import timedelta

BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(dotenv_path=os.path.join(BASE_DIR, ".env"))

# ...existing code...
# Build paths inside the project like this: BASE_DIR / 'subdir'.

APP_ENV = os.getenv("APP_ENV", "local")

# Plan Configuration
FREE_PLAN_URL_LIMIT = int(os.getenv("FREE_PLAN_URL_LIMIT", 3))
FREE_PLAN_DURATION_DAYS = int(os.getenv("FREE_PLAN_DURATION_DAYS", 7))
PAID_PLAN_URL_LIMIT = int(os.getenv("PAID_PLAN_URL_LIMIT", 50))
PREMIUM_PLAN_UNLIMITED = os.getenv("PREMIUM_PLAN_UNLIMITED", "true").lower() == "true"
PAID_PLAN_DURATION_DAYS = int(os.getenv("PAID_PLAN_DURATION_DAYS", 30))
PAID_PLAN_PRICE = float(os.getenv("PAID_PLAN_PRICE", 9.99))

# SSLCommerz Configuration
SSLCOMMERZ_STORE_ID = os.getenv("SSLCOMMERZ_STORE_ID", "")
SSLCOMMERZ_STORE_PASSWORD = os.getenv("SSLCOMMERZ_STORE_PASSWORD", "")
SSLCOMMERZ_IS_SANDBOX = os.getenv("SSLCOMMERZ_IS_SANDBOX", "true").lower() == "true"

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-f((yp1^pve6k-*tk8%0cjm_a$pm!y-psw(pir!dp2jha5(eq#t"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    "focusly-api.shadhin.ai",
    "block.shadhintech.com",
    "focusly.pro",
    "localhost",
    "127.0.0.1",
    "qa.focusly.pro",
    "stage.focusly.pro",
    "app.focusly.pro",
    "www.app.focusly.pro",
    ".focusly.pro",  # This will match all subdomains of focusly.pro
]
CSRF_TRUSTED_ORIGINS = [
    "https://block.shadhintech.com",
    "https://focusly.pro",
    "https://qa.focusly.pro",
    "https://stage.focusly.pro",
    "https://app.focusly.pro",
    "https://devapi.focusly.pro",
    "https://focusly-api.shadhin.ai",
]
CORS_ALLOWED_ORIGINS = [
    "https://focusly.pro",
    "https://block.shadhintech.com",
    "http://localhost:3000",
    "https://qa.focusly.pro",
    "https://stage.focusly.pro",
    "https://app.focusly.pro",
    "https://devapi.focusly.pro",
    "https://focusly-api.shadhin.ai",
]

# Add CORS_ORIGIN_WHITELIST as a fallback
CORS_ORIGIN_WHITELIST = [
    "https://focusly.pro",
    "https://block.shadhintech.com",
    "http://localhost:3000",
    "https://qa.focusly.pro",
    "https://stage.focusly.pro",
    "https://app.focusly.pro",
    "https://devapi.focusly.pro",
    "https://focusly-api.shadhin.ai",
]

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
]

CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
    "access-control-allow-origin",
    "access-control-allow-headers",
    "access-control-allow-methods",
]

# Add CORS_EXPOSE_HEADERS
CORS_EXPOSE_HEADERS = [
    "access-control-allow-origin",
    "access-control-allow-credentials",
]

# Ensure preflight requests are handled
CORS_PREFLIGHT_MAX_AGE = 86400  # 24 hours

# Application definition

INSTALLED_APPS = [
    # "django.contrib.admin",  # Removed Django admin
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corsheaders",
    "rest_framework",
    "rest_framework_simplejwt",
    "channels",
    "users",
    "subscriptions",
    "urlshandler",
    "analytics",
    "post_office",
    "django_crontab",
    "django_celery_beat",
]


EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "email-smtp.ap-south-1.amazonaws.com"
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False
EMAIL_PORT = 587
EMAIL_HOST_USER = "AKIARLGWYA43WRDN4AHM"
EMAIL_HOST_PASSWORD = "BPFOwEjqZER3tsWJQFZMSxo3yKBMwFZ8nZllSljeCbMr"
DEFAULT_FROM_EMAIL = "Focusly.pro <info@focusly.pro>"

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

POST_OFFICE = {
    "EMAIL_BACKEND": "django.core.mail.backends.smtp.EmailBackend",
    "DEFAULT_PRIORITY": "now",
}

ROOT_URLCONF = "productivity_plugin_api.urls"
STATIC_URL = "/static/"
STATIC_ROOT = os.getenv(
    "STATIC_ROOT", os.path.join(BASE_DIR, "static_root")
)  # Only define once
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "productivity_plugin_api.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

AUTH_USER_MODEL = "users.User"
print("APP_ENV:", APP_ENV)
print("Database Config:", DB_CONFIG[APP_ENV])
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": DB_CONFIG[APP_ENV]["DB_NAME"],
        "USER": DB_CONFIG[APP_ENV]["DB_USER"],
        "PASSWORD": DB_CONFIG[APP_ENV]["DB_PASSWORD"],
        "HOST": DB_CONFIG[APP_ENV]["DB_HOST"],
        "PORT": DB_CONFIG[APP_ENV]["DB_PORT"],
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

REST_FRAMEWORK = {
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated"
    ],
    "DEFAULT_AUTHENTICATION_CLASSES": [
        # Use your custom JWT authentication
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        # Removed session and basic auth to prevent conflicts with the browse-able API
        # "rest_framework.authentication.SessionAuthentication",
        # "rest_framework.authentication.BasicAuthentication",
    ],
    # Disable Browsable API for production
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
    ] if not DEBUG else [
        "rest_framework.renderers.JSONRenderer",
        "rest_framework.renderers.BrowsableAPIRenderer",
    ]
}

# REST_FRAMEWORK = {
#     'DEFAULT_AUTHENTICATION_CLASSES': (
#         'rest_framework.authentication.SessionAuthentication',
#         'rest_framework.authentication.BasicAuthentication',
#         'rest_framework_simplejwt.authentication.JWTAuthentication',  # Ensure this is added
#     ),
#     'DEFAULT_PERMISSION_CLASSES': [
#         'rest_framework.permissions.IsAuthenticated',  # Default to authenticated users
#         'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly'
#     ],
# }


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Dhaka"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

LOG_DIR = os.path.join(BASE_DIR, "logs")
os.makedirs(LOG_DIR, exist_ok=True)

# CRONJOBS = [
#     # Run every day at midnight (00:00)
#     (
#         "0 0 * * *",
#         "django.core.management.call_command",
#         ["reset_time"],
#         {},
#         f'>> {os.path.join(BASE_DIR, "logs/cron.log")} 2>&1',
#     )
# ]

CRONTAB_COMMAND_PREFIX = "DJANGO_SETTINGS_MODULE=productivity_plugin_api.settings"

# Celery Configuration
REDIS_HOST = os.getenv('REDIS_HOST', 'localhost')
REDIS_PORT = os.getenv('REDIS_PORT', '6379')
REDIS_DB = os.getenv('REDIS_DB', '0')
REDIS_URL = f'redis://{REDIS_HOST}:{REDIS_PORT}/{REDIS_DB}'
CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', REDIS_URL)
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', REDIS_URL)
CELERY_QUEUE_NAME = os.getenv('CELERY_QUEUE_NAME', 'productivity_queue')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Asia/Dhaka'  # Default timezone for Celery
CELERY_ENABLE_UTC = False
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'

# Channels Configuration
ASGI_APPLICATION = 'productivity_plugin_api.asgi.application'
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [('127.0.0.1', 6379)],
        },
    },
}

# SimpleJWT settings
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=525600),  # Match the custom implementation
    'SIGNING_KEY': SECRET_KEY,
    'ALGORITHM': 'HS256',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'id',  # Use 'id' instead of default 'user_id'
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
}

LOGS_DIR = os.path.join(BASE_DIR, 'logs')
os.makedirs(LOGS_DIR, exist_ok=True)
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{levelname}] {asctime} {name} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '[{levelname}] {asctime} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'DEBUG',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOGS_DIR, 'django_debug.log'),
            'maxBytes': 1024*1024*10,  # 10 MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
        'daphne_file': {
            'level': 'DEBUG',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOGS_DIR, 'daphne.log'),
            'maxBytes': 1024*1024*10,  # 10 MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file', 'console'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'daphne': {
            'handlers': ['daphne_file', 'console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        # Root logger to catch everything else
        '': {
            'handlers': ['file'],
            'level': 'DEBUG',
        },
    },
}